apiVersion: v2
name: gozone
description: A Helm chart for gozone
type: application
version: 0.4.2
appVersion: "0.5.2"
icon: https://avatars.githubusercontent.com/u/7756566?s=200&v=4

keywords:
- pdns
- admin
- api
- golang

sources:
- https://github.com/babykart/gozone.git

maintainers:
- name: babykart
  email: babykart@gmail.com
  url: https://github.com/babykart
