{{- if and (eq .Values.config.existingSecret "") .Values.config.gozoneConf }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gozone.fullname" . }}-config
  labels:
    {{- include "gozone.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config.gozoneConf | b64enc | quote }}
{{- end }}
